### ISSUE TITLE
TravisCI build failing for Python 3.7-dev

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/nexus_uploader#2]
This is due to PyYAML:
https://github.com/yaml/pyyaml/issues/126

**Comment by hugovk** [comment]
Good news: PyYAML 4.1 has been released which now installs successfully on Python 3.7:

https://github.com/yaml/pyyaml/issues/126#issuecomment-400679908

**Comment by Lucas-C** [comment]
Thanks ! Issue solved
